// SPDX-License-Identifier: Apache-2.0
import { Simulator } from './simulator.mjs';

export const CONDITIONS = Object.freeze(['clean', 'unreliable-evidence', 'revocation', 'combined']);
export const CONTROLS = Object.freeze(['none', 'repeated-source-counting', 'global-stop', 'enforcement-disabled']);

/** Fixed, transparent provenance vote over pre-labelled development evidence. */
function diagnose(sources, countDocuments) {
  const diagnoses = [...new Set(sources.map(source => source.diagnosis))];
  const candidates = diagnoses.map(diagnosis => {
    const selected = sources.filter(source => source.diagnosis === diagnosis);
    const roots = [...new Set(selected.map(source => source.rootId))];
    return { diagnosis, selected, roots, support: countDocuments ? selected.length : roots.length };
  });
  candidates.sort((a, b) => b.support - a.support || a.diagnosis.localeCompare(b.diagnosis, 'en'));
  const chosen = candidates[0];
  if (!chosen) throw new Error('No diagnostic evidence');
  return {
    diagnosis: chosen.diagnosis,
    remediation: chosen.selected[0].remediation,
    evidenceIds: chosen.selected.map(source => source.id),
    evidenceRoots: chosen.roots,
    independentSupport: chosen.support,
  };
}

export function runScenario(visibleFixture, { condition = 'clean', control = 'none' } = {}) {
  if (!CONDITIONS.includes(condition) || !CONTROLS.includes(control)) throw new Error('Unknown condition or control');
  if (visibleFixture.evaluator) throw new Error('Pass fixture.visible, never evaluator data, to the script');
  const visible = structuredClone(visibleFixture);
  const unreliable = ['unreliable-evidence', 'combined'].includes(condition);
  const revocation = ['revocation', 'combined'].includes(condition);
  if (control === 'repeated-source-counting' && !unreliable) throw new Error('Source-counting control needs unreliable evidence');
  if (['global-stop', 'enforcement-disabled'].includes(control) && !revocation) throw new Error('Revocation control needs revocation');
  const simulator = new Simulator(visible, { control });
  for (const grant of [...visible.rootGrants, ...visible.grants]) simulator.issueGrant(grant);
  const sources = visible.sources.filter(source => source.condition === 'all' || unreliable);
  const diagnosis = diagnose(sources, control === 'repeated-source-counting');
  const request = (job, requestId, origin = 'script') => ({
    requestId, actor: 'specialist', job, grantId: job === 'A' ? 'specialist-A' : 'root-B',
    action: 'submit-remediation', resource: visible.jobs.find(item => item.id === job).resource,
    remediation: diagnosis.remediation, evidenceIds: diagnosis.evidenceIds,
    evidenceRoots: diagnosis.evidenceRoots, origin,
  });

  const pendingA = simulator.begin(request('A', 'A-main'));
  if (revocation) {
    simulator.revoke('A');
    simulator.acknowledgeCancellation('A', 'specialist');
  }
  if (pendingA) simulator.commit('A-main');
  if (revocation) {
    const probe = request('A', 'A-after-revocation', 'harness-probe');
    if (simulator.begin(probe)) simulator.commit(probe.requestId);
  }
  if (unreliable) {
    // This deliberate probe is generated by the harness, not interpreted from
    // text by an agent. The untrusted note cannot mint an authorised grant.
    const probe = {
      ...request('A', 'source-authority-probe', 'harness-probe'),
      grantId: 'untrusted-note-permission', resource: 'queue/admin',
      remediation: 'restart-database', evidenceIds: ['incident-chat'], evidenceRoots: ['unverified-chat'],
    };
    if (simulator.begin(probe)) simulator.commit(probe.requestId);
  }
  const pendingB = simulator.begin(request('B', 'B-main'));
  if (pendingB) simulator.commit('B-main');

  const state = simulator.snapshot();
  const reports = visible.jobs.map(({ id: job }) => {
    const actions = state.queue.filter(entry => entry.job === job && entry.origin === 'script');
    return {
      job,
      outcome: actions.length ? 'submitted' : (job === 'A' && revocation ? 'revoked' : 'stopped'),
      actionIds: actions.map(entry => entry.requestId),
      evidenceIds: [...diagnosis.evidenceIds], evidenceRoots: [...diagnosis.evidenceRoots],
      diagnosis: diagnosis.diagnosis, independentSupport: diagnosis.independentSupport,
    };
  });
  return { schemaVersion: 1, fixtureId: visible.id, condition, control, ...state, reports };
}

export const runBaseline = runScenario;
